- label: Date of accident
  type: DATE_NOT_IN_FUTURE
  defaultValue: SYSDATE
- label: Product name
  type: TEXT
- label: Manufacturer's mark / address
  optional: true
  type: TEXT
- label: Identification elements (Model / Serial number / Volume / Weight)
  optional: true
  type: TEXT
- label: Did the person who consumed the food become sick and/or injured ?
  optional: true
  type: RADIO
  options:
    - "No"
    - Yes (to be specified)
- label: Have you already contacted the merchant or the manufacturer for this problem ?
  type: RADIO
  options:
    - "Yes"
    - "No"
