- label: Date of accident
  type: DATE
  defaultValue: SYSDATE
- label: Product Name
  type: TEXT
- label: Manufacturer's mark / address
  optional: true
  type: TEXT
- label: Identification elements (Model / Serial number / Volume / Weight)
  optional: true
  type: TEXT
- label: Did the person who consumed the food become ill and/or injured ?
  optional: true
  type: RADIO
  options:
    - 'No'
    - Yes (to be specified)
- label: Describe in more detail what happened
  type: TEXTAREA
- label: Have you already contacted the merchant or the manufacturer for this problem ?
  type: RADIO
  options:
    - 'Yes'
    - 'No'
