- title: Étouffement
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '344'
    - '346'
    - '347'
    - '352'
    - '345'
- title: Blessure physique
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '344'
    - '346'
    - '347'
    - '352'
    - '345'
- title: Choc électrique
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '344'
    - '345'
- title: Allergie
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '344'
    - '346'
    - '352'
    - '324'
    - '345'
- title: Risque environnemental
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
- title: Autre
  detailInputs: !!import/single ./inputs/produit-dangereux.yml
  fileLabel: Photos du produit / de la notice / du ticket / de la facture / de l'accident
