import type {GetStaticProps} from 'next'
import Head from 'next/head'
import {styled} from '@mui/material/styles'
import {IllustrationStepper, IllustrationStepperStep} from '../shared/IllustrationStepper/StepIllustrations'
import {Grid, useTheme} from '@mui/material'
import {apiSdk} from '../core/apiSdk'
import {Anomaly} from '@signal-conso/signalconso-api-sdk-js'
import {AnomalyCard} from '../shared/AnomalyCard/AnomalyCard'
import {serialiseJsonForStupidNextJs} from '../core/helper/utils'

const Banner = styled('section')(({theme}) => ({
  background: theme.palette.primary.main,
  color: theme.palette.primary.contrastText,
  textAlign: 'center',
  padding: theme.spacing(5),
  fontSize: 32,
  fontWeight: 'lighter',
}))

const Title = styled('h2')(({theme}) => ({
  fontSize: 24,
}))

const Section = styled('section')(({theme}) => ({
  padding: theme.spacing(3, 1),
}))

export const getStaticProps: GetStaticProps = async (context) => {
  const anomalies = await apiSdk.anomaly.getAnomalies().then(res => res.filter(_ => !_.hidden))
  return {
    props: serialiseJsonForStupidNextJs({
      anomalies
    }),
  }
}

// = InferGetStaticPropsType<typeof getStaticProps>
interface HomeProps {
  anomalies: Anomaly[]
}

const Home = ({anomalies}: HomeProps) => {
  const theme = useTheme()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Banner>
          Signaler un problème à <b>l&apos;entreprise</b> <br/>
          en toute transparence avec <b>la répression des fraudes</b> !
        </Banner>

        <Section>
          <Title>Comment ça marche ?</Title>
          <IllustrationStepper>
            <IllustrationStepperStep title="Vous avez rencontré un problème<br/>avec une entreprise&#160;?" image="/image/illustrations/consumer.png"/>
            <IllustrationStepperStep title="Faites un signalement<br/>avec SignalConso." image="/image/illustrations/report.png"/>
            <IllustrationStepperStep title="L'entreprise est prévenue<br/>et peut intervenir." image="/image/illustrations/company.png"/>
            <IllustrationStepperStep title="La répression des fraudes intervient si nécessaire." image="/image/illustrations/dgccrf.png"/>
          </IllustrationStepper>
        </Section>

        <Section>
          <Title>Quel problème avez-vous rencontré ?</Title>
          <Grid container spacing={2}>
            {anomalies.map(a => (
              <Grid key={a.path} item xs={12} sm={6} md={4}>
                <AnomalyCard anomaly={a}/>
              </Grid>
            ))}
          </Grid>
        </Section>
      </main>
    </>
  )
}

export default Home
