- label: Date de l'accident
  type: DATE_NOT_IN_FUTURE
  defaultValue: SYSDATE
- label: La personne qui a consommé l'aliment est-elle tombée malade et/ou s'est-elle blessée ?
  optional: true
  type: RADIO
  options:
    - Non
    - Oui (à préciser)
- label: Avez-vous déjà contacté le commerçant ou le fabricant pour ce problème ?
  type: RADIO
  options:
    - Oui
    - Non
