- label: Date de l'accident
  type: DATE
  defaultValue: SYSDATE
- label: Nom du produit
  type: TEXT
- label: Marque / adresse du fabriquant
  example: Indiquée sur l'emballage
  optionnal: true
  type: TEXT
- label: Élements d'identification (Modèle / N° de série / Volume / Poids)
  optionnal: true
  type: TEXT
- label: La personne qui a consommé l'aliment est-elle tombée malade et/ou s'est-elle blessée&#160;?
  optionnal: true
  type: RADIO
  example: Préciser la nature et la gravité
  options:
    - Non
    - Oui (à préciser)
- label: Décrivez nous plus en détails ce qui s'est passé
  type: TEXTAREA
- label: Avez-vous déjà contacté le commerçant ou le fabriquant pour ce problème&#160;?
  type: RADIO
  options:
    - Oui
    - Non
