import {Anomaly} from 'anomalies/Anomaly'
import {NewsArticle} from 'components_feature/actualites/newsArticlesData'
import {AppLang, AppLangs} from '../i18n/localization/AppLangs'
import {LandingData, allVisibleLandings} from '../landings/landingDataUtils'
import {appConfig} from './appConfig'

type PageDefExternal = {
  isExternal: true
  url: string
}
export type PageDefInternal = {
  isExternal: false
  url: string
  urlRelative: string
  noIndex: boolean
  //Has alternate language available for the page
  hasAlternate: boolean
}

function page(url: string, options: {noIndex?: boolean; hasAlternate?: boolean} = {}): PageDefInternal {
  const noIndex = options.noIndex ?? false
  const hasAlternate = options.hasAlternate ?? false
  return {
    isExternal: false,
    url,
    hasAlternate,
    // without the leading slash, it becomes a relative link
    // useful for preserving the /webview/ prefix
    urlRelative: url.slice(1),
    noIndex,
  }
}

function pageExternal(url: string): PageDefExternal {
  return {
    isExternal: true,
    url,
  }
}

export const internalPageDefs = {
  index: page('/', {hasAlternate: true}),
  arborescence: page(`/arborescence`, {noIndex: true, hasAlternate: true}),
  accessibilite: page(`/accessibilite`, {hasAlternate: true}),
  planDuSite: page(`/plan-du-site`, {hasAlternate: true}),
  actualites: page(`/actualites`, {hasAlternate: true}),
  // only on dev/demo
  ...(appConfig.showPlayground ? {playground: page(`/playground`, {noIndex: true, hasAlternate: true})} : {}),

  // all these are available in /webview/
  commentCaMarche: page(`/comment-ca-marche`, {hasAlternate: true}),
  conditionsGeneralesUtilisation: page(`/conditions-generales-utilisation`, {noIndex: true, hasAlternate: true}),
  contact: page(`/contact`, {noIndex: true, hasAlternate: true}),
  cookies: page(`/cookies`, {hasAlternate: true}),
  delaiRetractation: page(`/delai-de-retractation`, {hasAlternate: true}),
  quiSommesNous: page(`/qui-sommes-nous`, {hasAlternate: true}),
  stats: page(`/stats`, {hasAlternate: true}),
  suiviEtViePrivee: page(`/suivi-et-vie-privee`, {hasAlternate: true}),
  litige: page(`/litige`, {hasAlternate: true}),
}

const externalPageDefs = {
  centreAide: pageExternal('https://aide.signal.conso.gouv.fr'),
  espaceProWelcome: pageExternal(appConfig.dashboardBaseUrl),
  espaceProConnexion: pageExternal(appConfig.dashboardBaseUrl + '/connexion'),
  companyActivation: pageExternal(appConfig.dashboardBaseUrl + '/activation'),
  lostPassword: pageExternal(appConfig.dashboardBaseUrl + '/perte-mot-de-passe'),
}

// This lists only the simple, unique, hardcoded pages
// There is also
// - the /xxx/faire-un-signalement pages
// - the landing pages (/xxx)
// - the news articles (/actualites/xxx)
// - the review url (/avis/xxx)
// - the /webview/xxx pages
export const pagesDefs = {
  ...internalPageDefs,
  ...externalPageDefs,
}

export function buildLinkStartReport(
  anomaly: Pick<Anomaly, 'path'>,
  lang: AppLang,
  {
    isWebView,
  }: {
    isWebView: boolean
  } = {isWebView: false},
) {
  return isWebView ? `/${lang}/webview/${anomaly.path}` : `/${lang}/${anomaly.path}/faire-un-signalement`
}

export function buildLinkLandingPage(landingData: LandingData) {
  return `/${landingData.lang}/${landingData.url}`
}

// sometimes we need to link a specific landing
// it's hard to reference them in a typesafe way since they're autogenerated
export function buildHardcodedLinkLandingPageFr(url: string): string | undefined {
  const landingData = allVisibleLandings(AppLangs.fr).find(_ => _.url === url)
  return landingData && buildLinkLandingPage(landingData)
}

export function buildLinkLandingPageFromAnomaly(lang: AppLangs, anomaly: Pick<Anomaly, 'path'>) {
  const landings = allVisibleLandings(lang)
  const landing = landings.find(_ => _.url === anomaly.path)
  if (landing) {
    return `/${lang}/${landing.url}`
  }
  return undefined
}

export function buildLinkNewsArticle(article: NewsArticle, {withLangPrefix = false}: {withLangPrefix?: boolean} = {}) {
  return `${withLangPrefix ? `/${article.lang}` : ''}/actualites/${article.slug}`
}

export function buildLinkHomePickCategory() {
  return pagesDefs.index.url + `#${HP_START_REPORT_ANCHOR}`
}

export const HP_START_REPORT_ANCHOR = 'quel-probleme'
