- label: Date de l'accident
  type: DATE
  defaultValue: SYSDATE
- label: Nom du produit
  type: TEXT
- label: Marque / adresse du fabriquant
  optional: true
  type: TEXT
- label: Élements d'identification (Modèle / N° de série / Volume / Poids)
  optional: true
  type: TEXT
- label: La personne qui a utilisé le produit a-t-elle était blessée&#160;?
  optional: true
  type: RADIO
  options:
    - Non
    - Oui (à préciser)
- label: Décrivez nous plus en détails ce qui s'est passé
  type: TEXTAREA
- label: Avez-vous déjà contacté le commerçant ou le fabriquant pour ce problème&#160;?
  type: RADIO
  options:
    - Oui
    - Non
