export {default as IconSkype} from './SkypeIcon'
export {default as FacebookIcon} from './FacebookIcon'
export {default as TwitterIcon} from './TwitterIcon'
export {default as LinkedinIcon} from './LinkedinIcon'
export {default as GitHubIcon} from './GitHubIcon'
export {default as DownloadIcon} from './DownloadIcon'
