- title: Cela m'a rendu malade
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '323'
    - '324'
    - '273'
    - '321'
    - '274'
    - '210'
    - '322'
    - '311'
- title: Etouffement
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '311'
    - '321'
    - '324'
    - '274'
    - '210'
- title: Blessure physique
  example: "Exemple : morceau de verre ou de plastique dans l'aliment"
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '311'
- title: Mauvaise odeur, goût étrange, couleur suspecte
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '321'
    - '323'
    - '322'
    - '311'
- title: Aliment pourri ou moisi
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '321'
    - '322'
    - '323'
    - '311'
- title: Allergie
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '322'
    - '323'
    - '324'
    - '340'
    - '2734'
    - '2732'
- title: Emballage déformé
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  example: 'Exemple : boite de conserve bombée'
  reponseconsoCode:
    - '323'
    - '321'
    - '324'
    - '322'
    - '340'
- title: Autre
  detailInputs: !!import/single ./inputs/produit-alimentaire.yml
  fileLabel: Photos du produit / de l'emballage / du ticket / de la facture / de l'accident
  reponseconsoCode:
    - '340'
    - '324'
    - '322'
    - '323'
