- label: Date de l'accident
  type: DATE
  defaultValue: SYSDATE
- label: La personne qui a consommé l'aliment est-elle tombée malade et/ou s'est-elle blessée&#160;?
  optional: true
  type: RADIO
  options:
    - Non
    - Oui (à préciser)
- label: Décrivez nous plus en détails ce qui s'est passé
  type: TEXTAREA
- label: Avez-vous déjà contacté le commerçant ou le fabricant pour ce problème&#160;?
  type: RADIO
  options:
    - Oui
    - Non
