name:  Build, format & test workflow

on:
  push:
    paths-ignore:
      - 'website/**'
      - 'mobile-tools/**'

jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable
      - run: yarn workspace website checkformat
      - run: yarn workspace mobile-tools checkformat
      - run: yarn workspace website build
      - run: yarn workspace mobile-tools build
      - run: yarn workspace website test
      - run: yarn workspace mobile-tools test
