on:
  workflow_dispatch: # can be triggered manually on github
  push:
    branches:
      - main # will trigger when pushing something on main
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: node --version
      - run: yarn --version
      - run: yarn install --frozen-lockfile
      - run: yarn sanitize-anomalies-filenames
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.MANU_GITHUB_TOKEN }}
          commit_message: Auto commit after sanitization of anomalies filenames
