on:
  workflow_dispatch: # can be triggered manually on github
  push:
    paths:
      - 'shared/**'
    branches:
      - main # will trigger when pushing something on main

defaults:
  run:
    working-directory: ./shared

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHARLES_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: node --version
      - run: yarn --version
      - run: yarn install --immutable
      - run: yarn shared:sanitize-anomalies-filenames
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto commit after sanitization of anomalies filenames
