name: Sanitize the file/folder names within Anomalies YAML

on:
  # This action is only triggered manually
  workflow_dispatch:

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable
      - run: yarn h-clean
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto commit of anomalies sanitization
